FROM node:20.19.4-alpine AS node

WORKDIR /app

# USE DOCKER IGNORE TO NOT COPY NODE_MODULES AND OTHER UNECESSARY FILES
COPY . .

RUN yarn

RUN yarn build --outDir /build

# BEGIN SERVER PART

FROM nginx:stable-alpine AS server

COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY --from=node /build ./web-dev

COPY --from=node /build/index.html .

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]