version: '3.8'

services:
  frontend:
    build: .
    image: frontend-bb-extrato:prod
    container_name: bb-extrato-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_NODE_ENV=production
      - VITE_APP_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bb-extrato-network

networks:
  bb-extrato-network:
    driver: bridge
